# 🐼 Pandas - Class 1: Introduction & Setup
Welcome to your first class on **Pandas**. In this session, we'll learn what Pandas is, why we use it, and how to get started with Series and DataFrames.

## 1 What is Pandas and Why Use It?
Pandas is a powerful **Python library** for data analysis and manipulation.

Key points:
- Provides two main data structures: **Series** (1D) and **DataFrame** (2D).
- Makes working with tabular data easy and fast.
- Ideal for cleaning, transforming, and analyzing datasets.
- Works well with other libraries like NumPy, Matplotlib, and Scikit-Learn.

## 2 Installing & Importing Pandas
To install pandas, open your terminal or command prompt and run:
```bash
pip install pandas
```
Then, you can import it in Python as follows:

In [3]:
import numpy as np
import pandas as pd
a = [10,20,30,40]
a

[10, 20, 30, 40]

In [5]:
s = pd.Series(a)
s

0    10
1    20
2    30
3    40
dtype: int64

In [7]:
s = pd.Series(a,name = "Marks")
s

0    10
1    20
2    30
3    40
Name: Marks, dtype: int64

In [10]:
d = {"Nishant":90,"Prashant":12,"Santosh":95,"Vivek":92}
s2 = pd.Series(d,name="Marks")
s2

Nishant     90
Prashant    12
Santosh     95
Vivek       92
Name: Marks, dtype: int64

## 3 Understanding Series & DataFrame
- **Series**: One-dimensional labeled array, like a column in Excel.
- **DataFrame**: Two-dimensional table, similar to an Excel sheet or SQL table.

### Creating a Series from Python Lists or Dictionaries

In [11]:
d = {"Nishant":90,"Prashant":12,"Santosh":95,"Vivek":92}
s2 = pd.Series(d,name="Marks")
s2

Nishant     90
Prashant    12
Santosh     95
Vivek       92
Name: Marks, dtype: int64

### Creating a DataFrame

In [13]:
a = {
    "Name":["nishant","santosh","vivek","pratik"],
    "Marks":[30,29,45,21],
    "Subject":["physics","chemistry","mathematics","hindi"]
}
pd.Series(a)

Name              [nishant, santosh, vivek, pratik]
Marks                              [30, 29, 45, 21]
Subject    [physics, chemistry, mathematics, hindi]
dtype: object

In [14]:
pd.DataFrame(a)

      Name  Marks      Subject
0  nishant     30      physics
1  santosh     29    chemistry
2    vivek     45  mathematics
3   pratik     21        hindi

### Creating DataFrame from NumPy Arrays

In [19]:
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
df = pd.DataFrame(a,columns = ["A","B","C"])
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

### Reading CSV / Excel Files (Sneak Peek)
You can read external data using:
```python
pd.read_csv('file.csv')
```
```python
pd.read_excel('file.xlsx')
```
We will explore this in detail later.

---
**Summary**
- Pandas is a must-know library for data analysis.
- We learned about Series & DataFrames.
- We saw how to create them from lists, dictionaries, NumPy arrays, and got a sneak peek at CSV/Excel files.