# 🐼 Pandas - Class 3: Data Cleaning Essentials
Welcome to **Class 3** of our Pandas series. Today we’ll learn how to clean and prepare data for analysis.

## Handling Missing Values
Real-world datasets often have missing data. Pandas offers:
- `isna()` / `isnull()` → detect missing values (returns True/False)
- `dropna()` → remove missing values (rows/columns)
- `fillna()` → replace missing values with a given value or method (e.g., forward fill)

Always inspect how much data is missing before deciding to drop or fill.

In [ ]:
import pandas as pd
import numpy as np
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, None, 35, 40, None],
    "City": ["Delhi", "Mumbai", None, "Bangalore", "Chennai"],
    "Score": [85, 91, np.nan, 88, 95]
}

b = pd.DataFrame(a)

In [3]:
import pandas as pd
import numpy as np
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, None, 35, 40, None],
    "City": ["Delhi", "Mumbai", None, "Bangalore", "Chennai"],
    "Score": [85, 91, np.nan, 88, 95]
}

b = pd.DataFrame(a)
b.isna()

    Name    Age   City  Score
0  False  False  False  False
1  False   True  False  False
2  False  False   True   True
3  False  False  False  False
4  False   True  False  False

In [6]:
import pandas as pd
import numpy as np
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, None, 35, 40, None],
    "City": ["Delhi", "Mumbai", None, "Bangalore", "Chennai"],
    "Score": [85, 91, np.nan, 88, 95]
}

b = pd.DataFrame(a)
b.isna().sum()

Name     0
Age      2
City     1
Score    1
dtype: int64

In [8]:
b

      Name   Age       City  Score
0    Alice  25.0      Delhi   85.0
1      Bob   NaN     Mumbai   91.0
2  Charlie  35.0       None    NaN
3    David  40.0  Bangalore   88.0
4     Emma   NaN    Chennai   95.0

In [18]:
b['Age']=b['Age'].fillna(b['Age'].mean())
b

      Name        Age       City  Score
0    Alice  25.000000      Delhi   85.0
1      Bob  33.333333     Mumbai   91.0
2  Charlie  35.000000       None    NaN
3    David  40.000000  Bangalore   88.0
4     Emma  33.333333    Chennai   95.0

In [19]:
b['City']=b['City'].fillna(b['City'].mode())
b

      Name        Age       City  Score
0    Alice  25.000000      Delhi   85.0
1      Bob  33.333333     Mumbai   91.0
2  Charlie  35.000000      Delhi    NaN
3    David  40.000000  Bangalore   88.0
4     Emma  33.333333    Chennai   95.0

In [20]:
b['Score']=b['Score'].fillna(0)
b

      Name        Age       City  Score
0    Alice  25.000000      Delhi   85.0
1      Bob  33.333333     Mumbai   91.0
2  Charlie  35.000000      Delhi    0.0
3    David  40.000000  Bangalore   88.0
4     Emma  33.333333    Chennai   95.0

In [21]:
b.isna().sum()

Name     0
Age      0
City     0
Score    0
dtype: int64

## Changing Data Types (`astype`)
- Convert a column to a different type using `astype()`.
- Examples: converting strings to numbers, integers to floats, or columns to category.

Be careful: make sure the data is compatible with the new type!

In [ ]:
a = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "Score": [88, 92, 79, 85, 95]
}

b = pd.DataFrame(a)

In [22]:
b['Score'] = b['Score'].astype(float)
b

      Name        Age       City  Score
0    Alice  25.000000      Delhi   85.0
1      Bob  33.333333     Mumbai   91.0
2  Charlie  35.000000      Delhi    0.0
3    David  40.000000  Bangalore   88.0
4     Emma  33.333333    Chennai   95.0

## Replacing Values (`replace`)
- Use `replace()` to substitute specific values or patterns.
- Useful for cleaning labels, fixing typos, or mapping categories.

In [ ]:
data = {
    "City": ["Bhopal", "Indore", "Bhopal", "Ujjain"]
}

df = pd.DataFrame(data)
# Replace "Bhopal" with "Sehore"
df["City"] = df["City"].replace("Bhopal", "Sehore")

print(df)

In [23]:
c = b.copy()
b

      Name        Age       City  Score
0    Alice  25.000000      Delhi   85.0
1      Bob  33.333333     Mumbai   91.0
2  Charlie  35.000000      Delhi    0.0
3    David  40.000000  Bangalore   88.0
4     Emma  33.333333    Chennai   95.0

In [24]:
c['Score'] = c['Score'].replace({88.0:90.0,95.0:99.0})
c

      Name        Age       City  Score
0    Alice  25.000000      Delhi   85.0
1      Bob  33.333333     Mumbai   91.0
2  Charlie  35.000000      Delhi    0.0
3    David  40.000000  Bangalore   90.0
4     Emma  33.333333    Chennai   99.0

## Dropping Rows & Columns (`drop`)
- `drop(labels, axis=0)` → drop rows by index labels.
- `drop(labels, axis=1)` → drop columns by name.
- Use `inplace=True` if you want to modify the DataFrame directly.

In [25]:
c.drop(["Name"],axis=1)
c

      Name        Age       City  Score
0    Alice  25.000000      Delhi   85.0
1      Bob  33.333333     Mumbai   91.0
2  Charlie  35.000000      Delhi    0.0
3    David  40.000000  Bangalore   90.0
4     Emma  33.333333    Chennai   99.0

In [ ]:
# Drop a row
import pandas as pd

df = pd.DataFrame({
    "Name": ["Aman", "Riya", "Vikas"],
    "Age": [20, 21, 22]
})

# Row with index 1 remove
df = df.drop(1)

print(df)

    Name  Age
0   Aman   20
2  Vikas   22

In [26]:
c.drop(['Name'],axis=1)
c

      Name        Age       City  Score
0    Alice  25.000000      Delhi   85.0
1      Bob  33.333333     Mumbai   91.0
2  Charlie  35.000000      Delhi    0.0
3    David  40.000000  Bangalore   90.0
4     Emma  33.333333    Chennai   99.0

In [ ]:
c.drop(['Name'],axis=0)

In [ ]:
# Drop a column
df = pd.DataFrame({
    "Name": ["Aman", "Riya", "Vikas"],
    "Age": [20, 21, 22]
})
# Age column remove
df = df.drop("Age", axis=1)

print(df)

In [ ]:
# Modify dataframe
df = pd.DataFrame({
    "Name": ["Aman", "Riya", "Vikas"],
    "Age": [20, 21, 22]
})

# Directly modify DataFrame
df.drop("Age", axis=1, inplace=True)

print(df)

## Detecting & Removing Duplicates
- `duplicated()` → returns a Boolean Series marking duplicate rows.
- `drop_duplicates()` → remove duplicate rows.
- You can specify `subset` (columns) and `keep` ('first', 'last', or False).

In [ ]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "Bob", "David"],
    "Age": [25, 30, 35, 25, 30, 40],
    "Score": [88, 92, 79, 88, 92, 85]
}

df = pd.DataFrame(data)

In [29]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "Bob", "David"],
    "Age": [25, 30, 35, 25, 30, 40],
    "Score": [88, 92, 79, 88, 92, 85]
}

df = pd.DataFrame(data)
df

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
3    Alice   25     88
4      Bob   30     92
5    David   40     85

In [30]:
df.drop_duplicates()

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     79
5    David   40     85

## Mini Practice
1. Create a messy DataFrame with missing values, wrong data types, typos, extra columns, and duplicates.
2. Clean it step-by-step using what you learned:
   - Handle missing values
   - Change data types
   - Replace incorrect values
   - Drop unnecessary rows/columns
   - Remove duplicates

In [ ]:
import pandas as pd
import numpy as np

# 1. Create a messy DataFrame
data = {
    "Name": ["Alice", "Bob", "Chrlie", "David", "Alice", None],
    "Age": ["25", "30", None, "40", "25", "30"],      # ages stored as strings, with missing value
    "City": ["Delhi", "Mumbai", "Pun", "Bangalore", "Delhi", "Mumbai"],  # typo: "Pun" -> "Pune"
    "Score": [85, None, 78, 88, 85, 91],              # missing value in Score
    "Extra": ["x", "y", "z", "x", "y", "z"]           # extra column we don't really need
}

df = pd.DataFrame(data)

print("Original messy DataFrame:")
print(df)

# 2. Handle missing values
# Fill or drop as needed

# 3. Change data types
# Convert Age to int, Score to float, etc.

# 4. Replace incorrect values
# Fix 'Pun' -> 'Pune', maybe unify Name spellings if needed

# 5. Drop unnecessary rows/columns
# Remove 'Extra' or any row you don't want

# 6. Remove duplicates
# Use duplicated() and drop_duplicates()

# 7. Final clean DataFrame
# Print the cleaned DataFrame and check info()

Original messy DataFrame:
     Name   Age       City  Score Extra
0   Alice    25      Delhi   85.0     x
1     Bob    30     Mumbai    NaN     y
2  Chrlie  None        Pun   78.0     z
3   David    40  Bangalore   88.0     x
4   Alice    25      Delhi   85.0     y
5    None    30     Mumbai   91.0     z

---
## Summary
- Learned to handle missing values (`isna`, `dropna`, `fillna`).
- Converted column data types with `astype`.
- Cleaned up incorrect entries with `replace`.
- Removed unwanted rows/columns with `drop`.
- Detected and removed duplicates.